version: "2.1"

services:
  chsa-a1-00:
    build: ./
    image: chsa-exercises/ubuntu:16.04-a1
    container_name: chsa-a1-00
    hostname: chsa-a1-00
    command: ["bash", "-c", "tail -s 1 -f /dev/null"]
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro