version: "2.1"

services:
  chsa-c1-00:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-00
    image: chsa-exercises/ubuntu:16.04-c100
    container_name: chsa-c1-00
    hostname: chsa-c1-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub
      - ./assets/config-genesis.batch:/home/sysops/.sawtooth/config-genesis.batch

  chsa-c1-01:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-01
    image: chsa-exercises/ubuntu:16.04-c101
    container_name: chsa-c1-01
    hostname: chsa-c1-01
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      # - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub
      - ./assets/config-genesis.batch:/home/sysops/.sawtooth/config-genesis.batch

  chsa-c1-02:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-02
    image: chsa-exercises/ubuntu:16.04-c102
    container_name: chsa-c1-02
    hostname: chsa-c1-02
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      # - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub
      - ./assets/config-genesis.batch:/home/sysops/.sawtooth/config-genesis.batch

  chsa-c1-loadgen:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-loadgen
    image: chsa-exercises/ubuntu:16.04-c1loadgen
    container_name: chsa-c1-loadgen
    hostname: chsa-c1-loadgen
    volumes:
      - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub
