version: "2.1"

services:
  chsa-b4-00:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-b4-00
    image: chsa-exercises/ubuntu:16.04-b400
    container_name: chsa-b4-00
    hostname: chsa-b4-00
    expose:
      - 8800
      - 4004
      - 8000
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  chsa-b4-01:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-b4-01
    image: chsa-exercises/ubuntu:16.04-b401
    container_name: chsa-b4-01
    hostname: chsa-b4-01
    expose:
      - 8800
      - 4004
      - 8000
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  chsa-b4-02:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-b4-02
    image: chsa-exercises/ubuntu:16.04-b402
    container_name: chsa-b4-02
    hostname: chsa-b4-02
    expose:
      - 8800
      - 4004
      - 8000
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
