version: "2.1"

services:
  chsa-b6-00:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-b6-00
    image: chsa-exercises/ubuntu:16.04-b600
    container_name: chsa-b6-00
    hostname: chsa-b6-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  
  chsa-b6-01:
    image: amd64/influxdb:alpine
    container_name: chsa-b6-01
    hostname: chsa-b6-01
    expose:
      - 8086
    environment:
      INFLUXDB_DB: "metrics"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "{admin-pw}"
      INFLUXDB_USER: "lrdata"
      INFLUXDB_USER_PASSWORD: "{lrdata-pw}"
    command:
      - "-config"
      - "/etc/influxdb/influxdb.conf"
    volumes:
      - ./assets/chsa-b6-01/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  chsa-b6-02:
    image: grafana/grafana:7.1.5
    container_name: chsa-b6-02
    hostname: chsa-b6-02
    ports:
      - 53000:3000
    volumes:
      - ./assets/chsa-b6-02/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./assets/chsa-b6-02/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./assets/chsa-b6-02/sawtooth_performance.json:/grafana-dashboard-definitions/0/sawtooth/sawtooth_performance.json:ro
