version: "2.1"

services:
  chsa-a6-00:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a6-00
    image: chsa-exercises/ubuntu:16.04-a600
    container_name: chsa-a6-00
    hostname: chsa-a6-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  chsa-a6-01:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a6-01
    image: chsa-exercises/ubuntu:16.04-a601
    container_name: chsa-a6-01
    hostname: chsa-a6-01
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  chsa-a6-02:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a6-02
    image: chsa-exercises/ubuntu:16.04-a602
    container_name: chsa-a6-02
    hostname: chsa-a6-02
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
