version: "2.1"

services:
  chsa-a8-00:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a8-00
    image: chsa-exercises/ubuntu:16.04-a800
    container_name: chsa-a8-00
    hostname: chsa-a8-00
    expose:
      - 8800
      - 4004
      - 8000
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
